name: FISHFactor
channels:
  - conda-forge
  - defaults
dependencies:
  - pyro-ppl
  - pytorch
  - scipy
  - anndata
  - requests
  - gpytorch
  - pandas
  - scikit-learn
  - h5py
  - seaborn
  - matplotlib
  - numpy
  - jupyter
  - imageio
  - gitpython
  - python=3.10
  - tensorflow
  - tensorflow-probability
  - dill
  - squidpy
  - pyarrow
